[package]
name = "luna-input"
description = "Platform-neutral input events for Luna UI Rust."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
luna-core = { path = "../luna-core" }

[lints]
workspace = true
