[package]
name = "luna-panes"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
luna-core = { path = "../luna-core" }
luna-documents = { path = "../luna-documents" }

[lints]
workspace = true
